--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 3/13/2022 9:40:51 PM
-- Server version: 8.0.18
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE academia_new_db;

--
-- Drop table `doctrine_migration_versions`
--
DROP TABLE IF EXISTS doctrine_migration_versions;

--
-- Drop table `bill_billcard`
--
DROP TABLE IF EXISTS bill_billcard;

--
-- Drop table `bill_ligne_sortie_transfert`
--
DROP TABLE IF EXISTS bill_ligne_sortie_transfert;

--
-- Drop table `bill_ligne_damage`
--
DROP TABLE IF EXISTS bill_ligne_damage;

--
-- Drop table `bill_ligne_reuse`
--
DROP TABLE IF EXISTS bill_ligne_reuse;

--
-- Drop table `ligne_damage`
--
DROP TABLE IF EXISTS ligne_damage;

--
-- Drop table `bill_ligne_billcard`
--
DROP TABLE IF EXISTS bill_ligne_billcard;

--
-- Drop table `bill_ligne_controle`
--
DROP TABLE IF EXISTS bill_ligne_controle;

--
-- Drop table `bill_ligne_entree`
--
DROP TABLE IF EXISTS bill_ligne_entree;

--
-- Drop table `bill_ligne_sortie`
--
DROP TABLE IF EXISTS bill_ligne_sortie;

--
-- Drop table `bill_ligne_stock_controle`
--
DROP TABLE IF EXISTS bill_ligne_stock_controle;

--
-- Drop table `bill_ligne_transfert`
--
DROP TABLE IF EXISTS bill_ligne_transfert;

--
-- Drop table `ligne_controle`
--
DROP TABLE IF EXISTS ligne_controle;

--
-- Drop table `bill_produit_site`
--
DROP TABLE IF EXISTS bill_produit_site;

--
-- Drop table `bill_produit`
--
DROP TABLE IF EXISTS bill_produit;

--
-- Drop table `ligne_planification_enseignant`
--
DROP TABLE IF EXISTS ligne_planification_enseignant;

--
-- Drop table `ligne_planification`
--
DROP TABLE IF EXISTS ligne_planification;

--
-- Drop table `planification`
--
DROP TABLE IF EXISTS planification;

--
-- Drop table `salle`
--
DROP TABLE IF EXISTS salle;

--
-- Drop table `depot`
--
DROP TABLE IF EXISTS depot;

--
-- Drop table `ligne_cloture`
--
DROP TABLE IF EXISTS ligne_cloture;

--
-- Drop table `paiement_depot`
--
DROP TABLE IF EXISTS paiement_depot;

--
-- Drop table `proposition`
--
DROP TABLE IF EXISTS proposition;

--
-- Drop table `fiche`
--
DROP TABLE IF EXISTS fiche;

--
-- Drop table `message`
--
DROP TABLE IF EXISTS message;

--
-- Drop table `broadcast_message`
--
DROP TABLE IF EXISTS broadcast_message;

--
-- Drop table `cloture`
--
DROP TABLE IF EXISTS cloture;

--
-- Drop table `reset_password_request`
--
DROP TABLE IF EXISTS reset_password_request;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Drop table `enseignant`
--
DROP TABLE IF EXISTS enseignant;

--
-- Drop table `finaliste`
--
DROP TABLE IF EXISTS finaliste;

--
-- Drop table `identite`
--
DROP TABLE IF EXISTS identite;

--
-- Drop table `entreprise`
--
DROP TABLE IF EXISTS entreprise;

--
-- Drop table `promotion`
--
DROP TABLE IF EXISTS promotion;

--
-- Drop table `annee_academique`
--
DROP TABLE IF EXISTS annee_academique;

--
-- Drop table `departement`
--
DROP TABLE IF EXISTS departement;

--
-- Drop table `faculte`
--
DROP TABLE IF EXISTS faculte;

--
-- Drop table `bill_controle`
--
DROP TABLE IF EXISTS bill_controle;

--
-- Drop table `bill_entree`
--
DROP TABLE IF EXISTS bill_entree;

--
-- Drop table `bill_sortie`
--
DROP TABLE IF EXISTS bill_sortie;

--
-- Drop table `bill_transfert`
--
DROP TABLE IF EXISTS bill_transfert;

--
-- Drop table `controle`
--
DROP TABLE IF EXISTS controle;

--
-- Drop table `user_site`
--
DROP TABLE IF EXISTS user_site;

--
-- Drop table `bill_user`
--
DROP TABLE IF EXISTS bill_user;

--
-- Drop table `bill_site`
--
DROP TABLE IF EXISTS bill_site;

--
-- Drop table `bill_client`
--
DROP TABLE IF EXISTS bill_client;

--
-- Drop table `bill_fournisseur`
--
DROP TABLE IF EXISTS bill_fournisseur;

--
-- Drop table `bill_identite`
--
DROP TABLE IF EXISTS bill_identite;

--
-- Drop table `bill_ville`
--
DROP TABLE IF EXISTS bill_ville;

--
-- Set default database
--
USE academia_new_db;

--
-- Create table `bill_ville`
--
CREATE TABLE bill_ville (
  id INT(11) NOT NULL AUTO_INCREMENT,
  designation VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `UNIQ_75338C5D8947610D` on table `bill_ville`
--
ALTER TABLE bill_ville 
  ADD UNIQUE INDEX UNIQ_75338C5D8947610D(designation);

--
-- Create table `bill_identite`
--
CREATE TABLE bill_identite (
  id INT(11) NOT NULL AUTO_INCREMENT,
  ville_id INT(11) NOT NULL,
  telephone VARCHAR(255) NOT NULL,
  adresse VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_F3687B4AA73F0036` on table `bill_identite`
--
ALTER TABLE bill_identite 
  ADD INDEX IDX_F3687B4AA73F0036(ville_id);

--
-- Create foreign key
--
ALTER TABLE bill_identite 
  ADD CONSTRAINT FK_F3687B4AA73F0036 FOREIGN KEY (ville_id)
    REFERENCES bill_ville(id);

--
-- Create table `bill_fournisseur`
--
CREATE TABLE bill_fournisseur (
  id INT(11) NOT NULL AUTO_INCREMENT,
  ville_id INT(11) NOT NULL,
  telephone VARCHAR(255) NOT NULL,
  adresse VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL,
  noms VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_4781723FA73F0036` on table `bill_fournisseur`
--
ALTER TABLE bill_fournisseur 
  ADD INDEX IDX_4781723FA73F0036(ville_id);

--
-- Create index `UNIQ_4781723F77153098` on table `bill_fournisseur`
--
ALTER TABLE bill_fournisseur 
  ADD UNIQUE INDEX UNIQ_4781723F77153098(code);

--
-- Create foreign key
--
ALTER TABLE bill_fournisseur 
  ADD CONSTRAINT FK_4781723FA73F0036 FOREIGN KEY (ville_id)
    REFERENCES bill_ville(id);

--
-- Create table `bill_client`
--
CREATE TABLE bill_client (
  id INT(11) NOT NULL AUTO_INCREMENT,
  ville_id INT(11) NOT NULL,
  noms VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL,
  is_site TINYINT(1) NOT NULL,
  telephone VARCHAR(255) NOT NULL,
  adresse VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_D0C54A43A73F0036` on table `bill_client`
--
ALTER TABLE bill_client 
  ADD INDEX IDX_D0C54A43A73F0036(ville_id);

--
-- Create index `UNIQ_D0C54A4377153098` on table `bill_client`
--
ALTER TABLE bill_client 
  ADD UNIQUE INDEX UNIQ_D0C54A4377153098(code);

--
-- Create foreign key
--
ALTER TABLE bill_client 
  ADD CONSTRAINT FK_D0C54A43A73F0036 FOREIGN KEY (ville_id)
    REFERENCES bill_ville(id);

--
-- Create table `bill_site`
--
CREATE TABLE bill_site (
  id INT(11) NOT NULL AUTO_INCREMENT,
  ville_id INT(11) NOT NULL,
  site_client_id INT(11) NOT NULL,
  telephone VARCHAR(255) NOT NULL,
  adresse VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  designation VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL,
  is_warehouse TINYINT(1) NOT NULL,
  validation_attendu INT(11) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_9A5C614EA73F0036` on table `bill_site`
--
ALTER TABLE bill_site 
  ADD INDEX IDX_9A5C614EA73F0036(ville_id);

--
-- Create index `UNIQ_9A5C614E77153098` on table `bill_site`
--
ALTER TABLE bill_site 
  ADD UNIQUE INDEX UNIQ_9A5C614E77153098(code);

--
-- Create index `UNIQ_9A5C614E7FE11F54` on table `bill_site`
--
ALTER TABLE bill_site 
  ADD UNIQUE INDEX UNIQ_9A5C614E7FE11F54(site_client_id);

--
-- Create index `UNIQ_9A5C614E8947610D` on table `bill_site`
--
ALTER TABLE bill_site 
  ADD UNIQUE INDEX UNIQ_9A5C614E8947610D(designation);

--
-- Create foreign key
--
ALTER TABLE bill_site 
  ADD CONSTRAINT FK_9A5C614E7FE11F54 FOREIGN KEY (site_client_id)
    REFERENCES bill_client(id);

--
-- Create foreign key
--
ALTER TABLE bill_site 
  ADD CONSTRAINT FK_9A5C614EA73F0036 FOREIGN KEY (ville_id)
    REFERENCES bill_ville(id);

--
-- Create table `bill_user`
--
CREATE TABLE bill_user (
  id INT(11) NOT NULL AUTO_INCREMENT,
  site_actif_id INT(11) DEFAULT NULL,
  username VARCHAR(180) NOT NULL,
  roles LONGTEXT BINARY CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  password VARCHAR(255) NOT NULL,
  nom VARCHAR(255) NOT NULL,
  postnom VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  adresse VARCHAR(255) NOT NULL,
  telephone VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_7E8CBEE34CAC78F8` on table `bill_user`
--
ALTER TABLE bill_user 
  ADD INDEX IDX_7E8CBEE34CAC78F8(site_actif_id);

--
-- Create index `UNIQ_7E8CBEE3E7927C74` on table `bill_user`
--
ALTER TABLE bill_user 
  ADD UNIQUE INDEX UNIQ_7E8CBEE3E7927C74(email);

--
-- Create index `UNIQ_7E8CBEE3F85E0677` on table `bill_user`
--
ALTER TABLE bill_user 
  ADD UNIQUE INDEX UNIQ_7E8CBEE3F85E0677(username);

--
-- Create foreign key
--
ALTER TABLE bill_user 
  ADD CONSTRAINT FK_7E8CBEE34CAC78F8 FOREIGN KEY (site_actif_id)
    REFERENCES bill_site(id);

--
-- Create table `user_site`
--
CREATE TABLE user_site (
  user_id INT(11) NOT NULL,
  site_id INT(11) NOT NULL,
  PRIMARY KEY (user_id, site_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_13C2452DA76ED395` on table `user_site`
--
ALTER TABLE user_site 
  ADD INDEX IDX_13C2452DA76ED395(user_id);

--
-- Create index `IDX_13C2452DF6BD1646` on table `user_site`
--
ALTER TABLE user_site 
  ADD INDEX IDX_13C2452DF6BD1646(site_id);

--
-- Create foreign key
--
ALTER TABLE user_site 
  ADD CONSTRAINT FK_13C2452DA76ED395 FOREIGN KEY (user_id)
    REFERENCES bill_user(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE user_site 
  ADD CONSTRAINT FK_13C2452DF6BD1646 FOREIGN KEY (site_id)
    REFERENCES bill_site(id) ON DELETE CASCADE;

--
-- Create table `controle`
--
CREATE TABLE controle (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  site_id INT(11) NOT NULL,
  date DATE NOT NULL,
  observation_finale LONGTEXT DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_E39396EA76ED395` on table `controle`
--
ALTER TABLE controle 
  ADD INDEX IDX_E39396EA76ED395(user_id);

--
-- Create index `IDX_E39396EF6BD1646` on table `controle`
--
ALTER TABLE controle 
  ADD INDEX IDX_E39396EF6BD1646(site_id);

--
-- Create foreign key
--
ALTER TABLE controle 
  ADD CONSTRAINT FK_E39396EA76ED395 FOREIGN KEY (user_id)
    REFERENCES bill_user(id);

--
-- Create foreign key
--
ALTER TABLE controle 
  ADD CONSTRAINT FK_E39396EF6BD1646 FOREIGN KEY (site_id)
    REFERENCES bill_site(id);

--
-- Create table `bill_transfert`
--
CREATE TABLE bill_transfert (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  site_envoie_id INT(11) DEFAULT NULL,
  site_reception_id INT(11) DEFAULT NULL,
  date DATE NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  code VARCHAR(255) NOT NULL,
  is_validee TINYINT(1) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_F2A0A25324564208` on table `bill_transfert`
--
ALTER TABLE bill_transfert 
  ADD INDEX IDX_F2A0A25324564208(site_envoie_id);

--
-- Create index `IDX_F2A0A253A76ED395` on table `bill_transfert`
--
ALTER TABLE bill_transfert 
  ADD INDEX IDX_F2A0A253A76ED395(user_id);

--
-- Create index `IDX_F2A0A253B79E42E1` on table `bill_transfert`
--
ALTER TABLE bill_transfert 
  ADD INDEX IDX_F2A0A253B79E42E1(site_reception_id);

--
-- Create foreign key
--
ALTER TABLE bill_transfert 
  ADD CONSTRAINT FK_F2A0A25324564208 FOREIGN KEY (site_envoie_id)
    REFERENCES bill_site(id);

--
-- Create foreign key
--
ALTER TABLE bill_transfert 
  ADD CONSTRAINT FK_F2A0A253A76ED395 FOREIGN KEY (user_id)
    REFERENCES bill_user(id);

--
-- Create foreign key
--
ALTER TABLE bill_transfert 
  ADD CONSTRAINT FK_F2A0A253B79E42E1 FOREIGN KEY (site_reception_id)
    REFERENCES bill_site(id);

--
-- Create table `bill_sortie`
--
CREATE TABLE bill_sortie (
  id INT(11) NOT NULL AUTO_INCREMENT,
  client_id INT(11) DEFAULT NULL,
  user_id INT(11) NOT NULL,
  site_envoie_id INT(11) NOT NULL,
  date DATE NOT NULL,
  idd_number VARCHAR(255) DEFAULT NULL,
  machine_number VARCHAR(255) DEFAULT NULL,
  is_damage TINYINT(1) NOT NULL,
  code VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  is_sortie_speciale TINYINT(1) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_2BBE9DE419EB6921` on table `bill_sortie`
--
ALTER TABLE bill_sortie 
  ADD INDEX IDX_2BBE9DE419EB6921(client_id);

--
-- Create index `IDX_2BBE9DE424564208` on table `bill_sortie`
--
ALTER TABLE bill_sortie 
  ADD INDEX IDX_2BBE9DE424564208(site_envoie_id);

--
-- Create index `IDX_2BBE9DE4A76ED395` on table `bill_sortie`
--
ALTER TABLE bill_sortie 
  ADD INDEX IDX_2BBE9DE4A76ED395(user_id);

--
-- Create foreign key
--
ALTER TABLE bill_sortie 
  ADD CONSTRAINT FK_2BBE9DE419EB6921 FOREIGN KEY (client_id)
    REFERENCES bill_client(id);

--
-- Create foreign key
--
ALTER TABLE bill_sortie 
  ADD CONSTRAINT FK_2BBE9DE424564208 FOREIGN KEY (site_envoie_id)
    REFERENCES bill_site(id);

--
-- Create foreign key
--
ALTER TABLE bill_sortie 
  ADD CONSTRAINT FK_2BBE9DE4A76ED395 FOREIGN KEY (user_id)
    REFERENCES bill_user(id);

--
-- Create table `bill_entree`
--
CREATE TABLE bill_entree (
  id INT(11) NOT NULL AUTO_INCREMENT,
  site_reception_id INT(11) NOT NULL,
  fournisseur_id INT(11) DEFAULT NULL,
  user_id INT(11) NOT NULL,
  date DATE NOT NULL,
  numero_bon_fournisseur VARCHAR(255) DEFAULT NULL,
  code VARCHAR(255) NOT NULL,
  is_reuse TINYINT(1) NOT NULL,
  is_entree_speciale TINYINT(1) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_4E0239B0670C757F` on table `bill_entree`
--
ALTER TABLE bill_entree 
  ADD INDEX IDX_4E0239B0670C757F(fournisseur_id);

--
-- Create index `IDX_4E0239B0A76ED395` on table `bill_entree`
--
ALTER TABLE bill_entree 
  ADD INDEX IDX_4E0239B0A76ED395(user_id);

--
-- Create index `IDX_4E0239B0B79E42E1` on table `bill_entree`
--
ALTER TABLE bill_entree 
  ADD INDEX IDX_4E0239B0B79E42E1(site_reception_id);

--
-- Create index `UNIQ_4E0239B077153098` on table `bill_entree`
--
ALTER TABLE bill_entree 
  ADD UNIQUE INDEX UNIQ_4E0239B077153098(code);

--
-- Create foreign key
--
ALTER TABLE bill_entree 
  ADD CONSTRAINT FK_4E0239B0670C757F FOREIGN KEY (fournisseur_id)
    REFERENCES bill_fournisseur(id);

--
-- Create foreign key
--
ALTER TABLE bill_entree 
  ADD CONSTRAINT FK_4E0239B0A76ED395 FOREIGN KEY (user_id)
    REFERENCES bill_user(id);

--
-- Create foreign key
--
ALTER TABLE bill_entree 
  ADD CONSTRAINT FK_4E0239B0B79E42E1 FOREIGN KEY (site_reception_id)
    REFERENCES bill_site(id);

--
-- Create table `bill_controle`
--
CREATE TABLE bill_controle (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  site_id INT(11) NOT NULL,
  date DATE NOT NULL,
  code VARCHAR(255) NOT NULL,
  observation_finale LONGTEXT NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  is_validee TINYINT(1) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_83C5F7AFA76ED395` on table `bill_controle`
--
ALTER TABLE bill_controle 
  ADD INDEX IDX_83C5F7AFA76ED395(user_id);

--
-- Create index `IDX_83C5F7AFF6BD1646` on table `bill_controle`
--
ALTER TABLE bill_controle 
  ADD INDEX IDX_83C5F7AFF6BD1646(site_id);

--
-- Create foreign key
--
ALTER TABLE bill_controle 
  ADD CONSTRAINT FK_83C5F7AFA76ED395 FOREIGN KEY (user_id)
    REFERENCES bill_user(id);

--
-- Create foreign key
--
ALTER TABLE bill_controle 
  ADD CONSTRAINT FK_83C5F7AFF6BD1646 FOREIGN KEY (site_id)
    REFERENCES bill_site(id);

--
-- Create table `faculte`
--
CREATE TABLE faculte (
  id INT(11) NOT NULL AUTO_INCREMENT,
  designation VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  nombre_fiche_atraiter INT(11) NOT NULL,
  nombre_fiche_cree INT(11) NOT NULL,
  nombre_fiche_soumis INT(11) NOT NULL,
  nombre_fiche_validee INT(11) NOT NULL,
  nombre_fiche_feux_vert INT(11) NOT NULL,
  nombre_fiche_alignee INT(11) NOT NULL,
  nombre_fiche_defendu INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `departement`
--
CREATE TABLE departement (
  id INT(11) NOT NULL AUTO_INCREMENT,
  faculte_id INT(11) NOT NULL,
  designation VARCHAR(255) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_C1765B6372C3434F` on table `departement`
--
ALTER TABLE departement 
  ADD INDEX IDX_C1765B6372C3434F(faculte_id);

--
-- Create index `UNIQ_C1765B638947610D` on table `departement`
--
ALTER TABLE departement 
  ADD UNIQUE INDEX UNIQ_C1765B638947610D(designation);

--
-- Create foreign key
--
ALTER TABLE departement 
  ADD CONSTRAINT FK_C1765B6372C3434F FOREIGN KEY (faculte_id)
    REFERENCES faculte(id);

--
-- Create table `annee_academique`
--
CREATE TABLE annee_academique (
  id INT(11) NOT NULL AUTO_INCREMENT,
  debut INT(11) NOT NULL,
  fin INT(11) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  is_current TINYINT(1) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `UNIQ_A6971EA8AD2EF231` on table `annee_academique`
--
ALTER TABLE annee_academique 
  ADD UNIQUE INDEX UNIQ_A6971EA8AD2EF231(fin);

--
-- Create index `UNIQ_A6971EA8E81B0679` on table `annee_academique`
--
ALTER TABLE annee_academique 
  ADD UNIQUE INDEX UNIQ_A6971EA8E81B0679(debut);

--
-- Create table `promotion`
--
CREATE TABLE promotion (
  id INT(11) NOT NULL AUTO_INCREMENT,
  departement_id INT(11) NOT NULL,
  annee_academique_id INT(11) NOT NULL,
  faculte_id INT(11) NOT NULL,
  designation VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_C11D7DD172C3434F` on table `promotion`
--
ALTER TABLE promotion 
  ADD INDEX IDX_C11D7DD172C3434F(faculte_id);

--
-- Create index `IDX_C11D7DD1B00F076` on table `promotion`
--
ALTER TABLE promotion 
  ADD INDEX IDX_C11D7DD1B00F076(annee_academique_id);

--
-- Create index `IDX_C11D7DD1CCF9E01E` on table `promotion`
--
ALTER TABLE promotion 
  ADD INDEX IDX_C11D7DD1CCF9E01E(departement_id);

--
-- Create foreign key
--
ALTER TABLE promotion 
  ADD CONSTRAINT FK_C11D7DD172C3434F FOREIGN KEY (faculte_id)
    REFERENCES faculte(id);

--
-- Create foreign key
--
ALTER TABLE promotion 
  ADD CONSTRAINT FK_C11D7DD1B00F076 FOREIGN KEY (annee_academique_id)
    REFERENCES annee_academique(id);

--
-- Create foreign key
--
ALTER TABLE promotion 
  ADD CONSTRAINT FK_C11D7DD1CCF9E01E FOREIGN KEY (departement_id)
    REFERENCES departement(id);

--
-- Create table `entreprise`
--
CREATE TABLE entreprise (
  id INT(11) NOT NULL AUTO_INCREMENT,
  annee_academique_courante_id INT(11) NOT NULL,
  nom VARCHAR(255) NOT NULL,
  adresse VARCHAR(255) NOT NULL,
  ville VARCHAR(255) NOT NULL,
  pays VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  telephone1 VARCHAR(255) NOT NULL,
  telephone2 VARCHAR(255) DEFAULT NULL,
  website VARCHAR(255) NOT NULL,
  is_publique TINYINT(1) NOT NULL,
  sigle VARCHAR(255) NOT NULL,
  logo VARCHAR(255) NOT NULL,
  devise VARCHAR(255) NOT NULL,
  boite_postale VARCHAR(10) DEFAULT NULL,
  date_fin_proposition_sujet DATE NOT NULL,
  date_debut_defense_session1 DATE NOT NULL,
  date_debut_defense_session2 DATE NOT NULL,
  date_collation_grade DATE NOT NULL,
  prix_depot DOUBLE NOT NULL,
  monaie VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_D19FA6038878D1B` on table `entreprise`
--
ALTER TABLE entreprise 
  ADD INDEX IDX_D19FA6038878D1B(annee_academique_courante_id);

--
-- Create foreign key
--
ALTER TABLE entreprise 
  ADD CONSTRAINT FK_D19FA6038878D1B FOREIGN KEY (annee_academique_courante_id)
    REFERENCES annee_academique(id);

--
-- Create table `identite`
--
CREATE TABLE identite (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nom VARCHAR(255) NOT NULL,
  postnom VARCHAR(255) NOT NULL,
  prenom VARCHAR(255) NOT NULL,
  telephone VARCHAR(255) NOT NULL,
  adresse VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `finaliste`
--
CREATE TABLE finaliste (
  id INT(11) NOT NULL AUTO_INCREMENT,
  identite_id INT(11) NOT NULL,
  promotion_id INT(11) NOT NULL,
  faculte_id INT(11) DEFAULT NULL,
  nombre_correction_directeur INT(11) NOT NULL,
  civilite VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_242561BE139DF194` on table `finaliste`
--
ALTER TABLE finaliste 
  ADD INDEX IDX_242561BE139DF194(promotion_id);

--
-- Create index `IDX_242561BE72C3434F` on table `finaliste`
--
ALTER TABLE finaliste 
  ADD INDEX IDX_242561BE72C3434F(faculte_id);

--
-- Create index `UNIQ_242561BEE5F13C8F` on table `finaliste`
--
ALTER TABLE finaliste 
  ADD UNIQUE INDEX UNIQ_242561BEE5F13C8F(identite_id);

--
-- Create foreign key
--
ALTER TABLE finaliste 
  ADD CONSTRAINT FK_242561BE139DF194 FOREIGN KEY (promotion_id)
    REFERENCES promotion(id);

--
-- Create foreign key
--
ALTER TABLE finaliste 
  ADD CONSTRAINT FK_242561BE72C3434F FOREIGN KEY (faculte_id)
    REFERENCES faculte(id);

--
-- Create foreign key
--
ALTER TABLE finaliste 
  ADD CONSTRAINT FK_242561BEE5F13C8F FOREIGN KEY (identite_id)
    REFERENCES identite(id);

--
-- Create table `enseignant`
--
CREATE TABLE enseignant (
  id INT(11) NOT NULL AUTO_INCREMENT,
  identite_id INT(11) NOT NULL,
  is_cordirecteur TINYINT(1) NOT NULL,
  nombre_direction INT(11) DEFAULT NULL,
  nombre_feux_vert INT(11) DEFAULT NULL,
  nombre_nouveau_depot INT(11) NOT NULL,
  adresse_bureau VARCHAR(255) NOT NULL,
  grade VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `UNIQ_81A72FA1E5F13C8F` on table `enseignant`
--
ALTER TABLE enseignant 
  ADD UNIQUE INDEX UNIQ_81A72FA1E5F13C8F(identite_id);

--
-- Create foreign key
--
ALTER TABLE enseignant 
  ADD CONSTRAINT FK_81A72FA1E5F13C8F FOREIGN KEY (identite_id)
    REFERENCES identite(id);

--
-- Create table `user`
--
CREATE TABLE user (
  id INT(11) NOT NULL AUTO_INCREMENT,
  faculte_id INT(11) DEFAULT NULL,
  finaliste_id INT(11) DEFAULT NULL,
  enseignant_id INT(11) DEFAULT NULL,
  username VARCHAR(180) NOT NULL,
  roles JSON NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  nombre_message_non_lu INT(11) NOT NULL,
  photo VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_8D93D64972C3434F` on table `user`
--
ALTER TABLE user 
  ADD INDEX IDX_8D93D64972C3434F(faculte_id);

--
-- Create index `UNIQ_8D93D6499E6398AF` on table `user`
--
ALTER TABLE user 
  ADD UNIQUE INDEX UNIQ_8D93D6499E6398AF(finaliste_id);

--
-- Create index `UNIQ_8D93D649E455FCC0` on table `user`
--
ALTER TABLE user 
  ADD UNIQUE INDEX UNIQ_8D93D649E455FCC0(enseignant_id);

--
-- Create index `UNIQ_8D93D649F85E0677` on table `user`
--
ALTER TABLE user 
  ADD UNIQUE INDEX UNIQ_8D93D649F85E0677(username);

--
-- Create foreign key
--
ALTER TABLE user 
  ADD CONSTRAINT FK_8D93D64972C3434F FOREIGN KEY (faculte_id)
    REFERENCES faculte(id);

--
-- Create foreign key
--
ALTER TABLE user 
  ADD CONSTRAINT FK_8D93D6499E6398AF FOREIGN KEY (finaliste_id)
    REFERENCES finaliste(id);

--
-- Create foreign key
--
ALTER TABLE user 
  ADD CONSTRAINT FK_8D93D649E455FCC0 FOREIGN KEY (enseignant_id)
    REFERENCES enseignant(id);

--
-- Create table `reset_password_request`
--
CREATE TABLE reset_password_request (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  selector VARCHAR(20) NOT NULL,
  hashed_token VARCHAR(100) NOT NULL,
  requested_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)',
  expires_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_7CE748AA76ED395` on table `reset_password_request`
--
ALTER TABLE reset_password_request 
  ADD INDEX IDX_7CE748AA76ED395(user_id);

--
-- Create foreign key
--
ALTER TABLE reset_password_request 
  ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id)
    REFERENCES user(id);

--
-- Create table `cloture`
--
CREATE TABLE cloture (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  date DATE NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_D5D0B568A76ED395` on table `cloture`
--
ALTER TABLE cloture 
  ADD INDEX IDX_D5D0B568A76ED395(user_id);

--
-- Create foreign key
--
ALTER TABLE cloture 
  ADD CONSTRAINT FK_D5D0B568A76ED395 FOREIGN KEY (user_id)
    REFERENCES user(id);

--
-- Create table `broadcast_message`
--
CREATE TABLE broadcast_message (
  id INT(11) NOT NULL AUTO_INCREMENT,
  expediteur_id INT(11) NOT NULL,
  titre VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL,
  groupe_destinataire VARCHAR(255) NOT NULL,
  contenu LONGTEXT NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_26AEADCE10335F61` on table `broadcast_message`
--
ALTER TABLE broadcast_message 
  ADD INDEX IDX_26AEADCE10335F61(expediteur_id);

--
-- Create foreign key
--
ALTER TABLE broadcast_message 
  ADD CONSTRAINT FK_26AEADCE10335F61 FOREIGN KEY (expediteur_id)
    REFERENCES user(id);

--
-- Create table `message`
--
CREATE TABLE message (
  id INT(11) NOT NULL AUTO_INCREMENT,
  broadcast_message_id INT(11) NOT NULL,
  user_receiver_id INT(11) NOT NULL,
  created_at DATETIME NOT NULL,
  is_non_lu TINYINT(1) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_B6BD307F64482423` on table `message`
--
ALTER TABLE message 
  ADD INDEX IDX_B6BD307F64482423(user_receiver_id);

--
-- Create index `IDX_B6BD307FD7B73217` on table `message`
--
ALTER TABLE message 
  ADD INDEX IDX_B6BD307FD7B73217(broadcast_message_id);

--
-- Create foreign key
--
ALTER TABLE message 
  ADD CONSTRAINT FK_B6BD307F64482423 FOREIGN KEY (user_receiver_id)
    REFERENCES user(id);

--
-- Create foreign key
--
ALTER TABLE message 
  ADD CONSTRAINT FK_B6BD307FD7B73217 FOREIGN KEY (broadcast_message_id)
    REFERENCES broadcast_message(id);

--
-- Create table `fiche`
--
CREATE TABLE fiche (
  id INT(11) NOT NULL AUTO_INCREMENT,
  directeur_propose_id INT(11) NOT NULL,
  directeur_retenu_id INT(11) DEFAULT NULL,
  codirecteur_id INT(11) DEFAULT NULL,
  finaliste_id INT(11) NOT NULL,
  promotion_id INT(11) NOT NULL,
  faculte_id INT(11) NOT NULL,
  annee_academique_id INT(11) NOT NULL,
  date DATE NOT NULL,
  numero VARCHAR(255) NOT NULL,
  is_validee TINYINT(1) NOT NULL,
  is_soumis TINYINT(1) NOT NULL,
  observation LONGTEXT DEFAULT NULL,
  etat_fiche INT(11) DEFAULT NULL,
  is_feux_vert TINYINT(1) DEFAULT NULL,
  date_affectation DATETIME DEFAULT NULL,
  sujet_retenu LONGTEXT DEFAULT NULL,
  date_validation DATE DEFAULT NULL,
  is_planifiee TINYINT(1) NOT NULL,
  date_defense DATETIME DEFAULT NULL,
  date_soumission DATE DEFAULT NULL,
  date_feux_vert DATETIME DEFAULT NULL,
  is_paiement_depot TINYINT(1) NOT NULL,
  is_defendue TINYINT(1) NOT NULL,
  is_rejete TINYINT(1) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_4C13CC78139DF194` on table `fiche`
--
ALTER TABLE fiche 
  ADD INDEX IDX_4C13CC78139DF194(promotion_id);

--
-- Create index `IDX_4C13CC7872C3434F` on table `fiche`
--
ALTER TABLE fiche 
  ADD INDEX IDX_4C13CC7872C3434F(faculte_id);

--
-- Create index `IDX_4C13CC789B7F64D9` on table `fiche`
--
ALTER TABLE fiche 
  ADD INDEX IDX_4C13CC789B7F64D9(codirecteur_id);

--
-- Create index `IDX_4C13CC789FA86DF5` on table `fiche`
--
ALTER TABLE fiche 
  ADD INDEX IDX_4C13CC789FA86DF5(directeur_propose_id);

--
-- Create index `IDX_4C13CC78B00F076` on table `fiche`
--
ALTER TABLE fiche 
  ADD INDEX IDX_4C13CC78B00F076(annee_academique_id);

--
-- Create index `IDX_4C13CC78B0F3904E` on table `fiche`
--
ALTER TABLE fiche 
  ADD INDEX IDX_4C13CC78B0F3904E(directeur_retenu_id);

--
-- Create index `UNIQ_4C13CC789E6398AF` on table `fiche`
--
ALTER TABLE fiche 
  ADD UNIQUE INDEX UNIQ_4C13CC789E6398AF(finaliste_id);

--
-- Create foreign key
--
ALTER TABLE fiche 
  ADD CONSTRAINT FK_4C13CC78139DF194 FOREIGN KEY (promotion_id)
    REFERENCES promotion(id);

--
-- Create foreign key
--
ALTER TABLE fiche 
  ADD CONSTRAINT FK_4C13CC7872C3434F FOREIGN KEY (faculte_id)
    REFERENCES faculte(id);

--
-- Create foreign key
--
ALTER TABLE fiche 
  ADD CONSTRAINT FK_4C13CC789B7F64D9 FOREIGN KEY (codirecteur_id)
    REFERENCES enseignant(id);

--
-- Create foreign key
--
ALTER TABLE fiche 
  ADD CONSTRAINT FK_4C13CC789E6398AF FOREIGN KEY (finaliste_id)
    REFERENCES finaliste(id);

--
-- Create foreign key
--
ALTER TABLE fiche 
  ADD CONSTRAINT FK_4C13CC789FA86DF5 FOREIGN KEY (directeur_propose_id)
    REFERENCES enseignant(id);

--
-- Create foreign key
--
ALTER TABLE fiche 
  ADD CONSTRAINT FK_4C13CC78B00F076 FOREIGN KEY (annee_academique_id)
    REFERENCES annee_academique(id);

--
-- Create foreign key
--
ALTER TABLE fiche 
  ADD CONSTRAINT FK_4C13CC78B0F3904E FOREIGN KEY (directeur_retenu_id)
    REFERENCES enseignant(id);

--
-- Create table `proposition`
--
CREATE TABLE proposition (
  id INT(11) NOT NULL AUTO_INCREMENT,
  fiche_id INT(11) NOT NULL,
  sujet VARCHAR(255) NOT NULL,
  resume LONGTEXT NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_C7CDC353DF522508` on table `proposition`
--
ALTER TABLE proposition 
  ADD INDEX IDX_C7CDC353DF522508(fiche_id);

--
-- Create foreign key
--
ALTER TABLE proposition 
  ADD CONSTRAINT FK_C7CDC353DF522508 FOREIGN KEY (fiche_id)
    REFERENCES fiche(id);

--
-- Create table `paiement_depot`
--
CREATE TABLE paiement_depot (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  fiche_id INT(11) NOT NULL,
  date DATETIME NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_EF0C6EA3A76ED395` on table `paiement_depot`
--
ALTER TABLE paiement_depot 
  ADD INDEX IDX_EF0C6EA3A76ED395(user_id);

--
-- Create index `UNIQ_EF0C6EA3DF522508` on table `paiement_depot`
--
ALTER TABLE paiement_depot 
  ADD UNIQUE INDEX UNIQ_EF0C6EA3DF522508(fiche_id);

--
-- Create foreign key
--
ALTER TABLE paiement_depot 
  ADD CONSTRAINT FK_EF0C6EA3A76ED395 FOREIGN KEY (user_id)
    REFERENCES user(id);

--
-- Create foreign key
--
ALTER TABLE paiement_depot 
  ADD CONSTRAINT FK_EF0C6EA3DF522508 FOREIGN KEY (fiche_id)
    REFERENCES fiche(id);

--
-- Create table `ligne_cloture`
--
CREATE TABLE ligne_cloture (
  id INT(11) NOT NULL AUTO_INCREMENT,
  fiche_id INT(11) NOT NULL,
  cote DOUBLE NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `UNIQ_4A498B51DF522508` on table `ligne_cloture`
--
ALTER TABLE ligne_cloture 
  ADD UNIQUE INDEX UNIQ_4A498B51DF522508(fiche_id);

--
-- Create foreign key
--
ALTER TABLE ligne_cloture 
  ADD CONSTRAINT FK_4A498B51DF522508 FOREIGN KEY (fiche_id)
    REFERENCES fiche(id);

--
-- Create table `depot`
--
CREATE TABLE depot (
  id INT(11) NOT NULL AUTO_INCREMENT,
  fiche_id INT(11) NOT NULL,
  date DATETIME NOT NULL,
  fichier VARCHAR(255) DEFAULT NULL,
  note_etudiant LONGTEXT NOT NULL,
  note_directeur LONGTEXT DEFAULT NULL,
  is_corrige TINYINT(1) NOT NULL,
  fichier_corrige_directeur VARCHAR(255) DEFAULT NULL,
  date_depot DATE NOT NULL,
  date_correction DATE DEFAULT NULL,
  demandez_rendez_vous TINYINT(1) NOT NULL,
  date_rendez_vous DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_47948BBCDF522508` on table `depot`
--
ALTER TABLE depot 
  ADD INDEX IDX_47948BBCDF522508(fiche_id);

--
-- Create foreign key
--
ALTER TABLE depot 
  ADD CONSTRAINT FK_47948BBCDF522508 FOREIGN KEY (fiche_id)
    REFERENCES fiche(id);

--
-- Create table `salle`
--
CREATE TABLE salle (
  id INT(11) NOT NULL AUTO_INCREMENT,
  designation VARCHAR(255) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `UNIQ_4E977E5C8947610D` on table `salle`
--
ALTER TABLE salle 
  ADD UNIQUE INDEX UNIQ_4E977E5C8947610D(designation);

--
-- Create table `planification`
--
CREATE TABLE planification (
  id INT(11) NOT NULL AUTO_INCREMENT,
  salle_id INT(11) NOT NULL,
  date DATETIME NOT NULL,
  is_validee TINYINT(1) NOT NULL,
  observation VARCHAR(255) DEFAULT NULL,
  minutes_defense INT(11) NOT NULL,
  minutes_pause INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_FFC02E1BDC304035` on table `planification`
--
ALTER TABLE planification 
  ADD INDEX IDX_FFC02E1BDC304035(salle_id);

--
-- Create foreign key
--
ALTER TABLE planification 
  ADD CONSTRAINT FK_FFC02E1BDC304035 FOREIGN KEY (salle_id)
    REFERENCES salle(id);

--
-- Create table `ligne_planification`
--
CREATE TABLE ligne_planification (
  id INT(11) NOT NULL AUTO_INCREMENT,
  fiche_id INT(11) NOT NULL,
  planification_id INT(11) NOT NULL,
  heure_debut DATETIME NOT NULL,
  heure_fin DATETIME NOT NULL,
  observation VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_F4A32F7AE65142C2` on table `ligne_planification`
--
ALTER TABLE ligne_planification 
  ADD INDEX IDX_F4A32F7AE65142C2(planification_id);

--
-- Create index `UNIQ_F4A32F7ADF522508` on table `ligne_planification`
--
ALTER TABLE ligne_planification 
  ADD UNIQUE INDEX UNIQ_F4A32F7ADF522508(fiche_id);

--
-- Create foreign key
--
ALTER TABLE ligne_planification 
  ADD CONSTRAINT FK_F4A32F7ADF522508 FOREIGN KEY (fiche_id)
    REFERENCES fiche(id);

--
-- Create foreign key
--
ALTER TABLE ligne_planification 
  ADD CONSTRAINT FK_F4A32F7AE65142C2 FOREIGN KEY (planification_id)
    REFERENCES planification(id);

--
-- Create table `ligne_planification_enseignant`
--
CREATE TABLE ligne_planification_enseignant (
  ligne_planification_id INT(11) NOT NULL,
  enseignant_id INT(11) NOT NULL,
  PRIMARY KEY (ligne_planification_id, enseignant_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_E63F296A62E4E27D` on table `ligne_planification_enseignant`
--
ALTER TABLE ligne_planification_enseignant 
  ADD INDEX IDX_E63F296A62E4E27D(ligne_planification_id);

--
-- Create index `IDX_E63F296AE455FCC0` on table `ligne_planification_enseignant`
--
ALTER TABLE ligne_planification_enseignant 
  ADD INDEX IDX_E63F296AE455FCC0(enseignant_id);

--
-- Create foreign key
--
ALTER TABLE ligne_planification_enseignant 
  ADD CONSTRAINT FK_E63F296A62E4E27D FOREIGN KEY (ligne_planification_id)
    REFERENCES ligne_planification(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE ligne_planification_enseignant 
  ADD CONSTRAINT FK_E63F296AE455FCC0 FOREIGN KEY (enseignant_id)
    REFERENCES enseignant(id) ON DELETE CASCADE;

--
-- Create table `bill_produit`
--
CREATE TABLE bill_produit (
  id INT(11) NOT NULL AUTO_INCREMENT,
  pn VARCHAR(255) DEFAULT NULL,
  description VARCHAR(255) NOT NULL,
  quantite DOUBLE NOT NULL,
  prix_vente DOUBLE NOT NULL,
  stock_alerte DOUBLE NOT NULL,
  is_danger_stock TINYINT(1) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `bill_produit_site`
--
CREATE TABLE bill_produit_site (
  id INT(11) NOT NULL AUTO_INCREMENT,
  produit_id INT(11) NOT NULL,
  site_id INT(11) NOT NULL,
  quantite DOUBLE NOT NULL,
  is_produit_depot TINYINT(1) NOT NULL,
  stock_alerte DOUBLE NOT NULL,
  is_danger_stock TINYINT(1) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_3E1B170EF347EFB` on table `bill_produit_site`
--
ALTER TABLE bill_produit_site 
  ADD INDEX IDX_3E1B170EF347EFB(produit_id);

--
-- Create index `IDX_3E1B170EF6BD1646` on table `bill_produit_site`
--
ALTER TABLE bill_produit_site 
  ADD INDEX IDX_3E1B170EF6BD1646(site_id);

--
-- Create foreign key
--
ALTER TABLE bill_produit_site 
  ADD CONSTRAINT FK_3E1B170EF347EFB FOREIGN KEY (produit_id)
    REFERENCES bill_produit(id);

--
-- Create foreign key
--
ALTER TABLE bill_produit_site 
  ADD CONSTRAINT FK_3E1B170EF6BD1646 FOREIGN KEY (site_id)
    REFERENCES bill_site(id);

--
-- Create table `ligne_controle`
--
CREATE TABLE ligne_controle (
  id INT(11) NOT NULL AUTO_INCREMENT,
  controle_id INT(11) DEFAULT NULL,
  produit_site_id INT(11) DEFAULT NULL,
  quantite_physique DOUBLE NOT NULL,
  observation LONGTEXT DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_51A3285830469D3F` on table `ligne_controle`
--
ALTER TABLE ligne_controle 
  ADD INDEX IDX_51A3285830469D3F(produit_site_id);

--
-- Create index `IDX_51A32858758926A6` on table `ligne_controle`
--
ALTER TABLE ligne_controle 
  ADD INDEX IDX_51A32858758926A6(controle_id);

--
-- Create foreign key
--
ALTER TABLE ligne_controle 
  ADD CONSTRAINT FK_51A3285830469D3F FOREIGN KEY (produit_site_id)
    REFERENCES bill_produit_site(id);

--
-- Create foreign key
--
ALTER TABLE ligne_controle 
  ADD CONSTRAINT FK_51A32858758926A6 FOREIGN KEY (controle_id)
    REFERENCES controle(id);

--
-- Create table `bill_ligne_transfert`
--
CREATE TABLE bill_ligne_transfert (
  id INT(11) NOT NULL AUTO_INCREMENT,
  produit_site_id INT(11) NOT NULL,
  transfert_id INT(11) NOT NULL,
  quantite DOUBLE NOT NULL,
  observation VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_2D49B7230469D3F` on table `bill_ligne_transfert`
--
ALTER TABLE bill_ligne_transfert 
  ADD INDEX IDX_2D49B7230469D3F(produit_site_id);

--
-- Create index `IDX_2D49B723C9C4BAD` on table `bill_ligne_transfert`
--
ALTER TABLE bill_ligne_transfert 
  ADD INDEX IDX_2D49B723C9C4BAD(transfert_id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_transfert 
  ADD CONSTRAINT FK_2D49B7230469D3F FOREIGN KEY (produit_site_id)
    REFERENCES bill_produit_site(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_transfert 
  ADD CONSTRAINT FK_2D49B723C9C4BAD FOREIGN KEY (transfert_id)
    REFERENCES bill_transfert(id);

--
-- Create table `bill_ligne_stock_controle`
--
CREATE TABLE bill_ligne_stock_controle (
  id INT(11) NOT NULL AUTO_INCREMENT,
  site_id INT(11) NOT NULL,
  produit_site_id INT(11) NOT NULL,
  ligne_transfert_id INT(11) DEFAULT NULL,
  date DATE NOT NULL,
  machine_number VARCHAR(255) DEFAULT NULL,
  delivery_note_number VARCHAR(255) NOT NULL,
  quantity_received DOUBLE DEFAULT NULL,
  supplier VARCHAR(255) NOT NULL,
  customer VARCHAR(255) NOT NULL,
  ijd_number VARCHAR(255) NOT NULL,
  quantity_sold DOUBLE DEFAULT NULL,
  total_balance DOUBLE NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  numero_dnn INT(11) NOT NULL,
  numero_mouvement INT(11) NOT NULL,
  ligne_stock_controle_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_DEF547E530469D3F` on table `bill_ligne_stock_controle`
--
ALTER TABLE bill_ligne_stock_controle 
  ADD INDEX IDX_DEF547E530469D3F(produit_site_id);

--
-- Create index `IDX_DEF547E584420B62` on table `bill_ligne_stock_controle`
--
ALTER TABLE bill_ligne_stock_controle 
  ADD INDEX IDX_DEF547E584420B62(ligne_transfert_id);

--
-- Create index `IDX_DEF547E5F6BD1646` on table `bill_ligne_stock_controle`
--
ALTER TABLE bill_ligne_stock_controle 
  ADD INDEX IDX_DEF547E5F6BD1646(site_id);

--
-- Create index `UNIQ_DEF547E5F11D9B2F` on table `bill_ligne_stock_controle`
--
ALTER TABLE bill_ligne_stock_controle 
  ADD UNIQUE INDEX UNIQ_DEF547E5F11D9B2F(ligne_stock_controle_id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_stock_controle 
  ADD CONSTRAINT FK_DEF547E530469D3F FOREIGN KEY (produit_site_id)
    REFERENCES bill_produit_site(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_stock_controle 
  ADD CONSTRAINT FK_DEF547E584420B62 FOREIGN KEY (ligne_transfert_id)
    REFERENCES bill_ligne_transfert(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_stock_controle 
  ADD CONSTRAINT FK_DEF547E5F11D9B2F FOREIGN KEY (ligne_stock_controle_id)
    REFERENCES bill_ligne_stock_controle(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_stock_controle 
  ADD CONSTRAINT FK_DEF547E5F6BD1646 FOREIGN KEY (site_id)
    REFERENCES bill_site(id);

--
-- Create table `bill_ligne_sortie`
--
CREATE TABLE bill_ligne_sortie (
  id INT(11) NOT NULL AUTO_INCREMENT,
  sortie_id INT(11) NOT NULL,
  produit_site_id INT(11) NOT NULL,
  quantite DOUBLE NOT NULL,
  observation VARCHAR(255) DEFAULT NULL,
  ligne_stock_controle_id INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_64252CB130469D3F` on table `bill_ligne_sortie`
--
ALTER TABLE bill_ligne_sortie 
  ADD INDEX IDX_64252CB130469D3F(produit_site_id);

--
-- Create index `IDX_64252CB1CC72D953` on table `bill_ligne_sortie`
--
ALTER TABLE bill_ligne_sortie 
  ADD INDEX IDX_64252CB1CC72D953(sortie_id);

--
-- Create index `UNIQ_64252CB1F11D9B2F` on table `bill_ligne_sortie`
--
ALTER TABLE bill_ligne_sortie 
  ADD UNIQUE INDEX UNIQ_64252CB1F11D9B2F(ligne_stock_controle_id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_sortie 
  ADD CONSTRAINT FK_64252CB130469D3F FOREIGN KEY (produit_site_id)
    REFERENCES bill_produit_site(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_sortie 
  ADD CONSTRAINT FK_64252CB1CC72D953 FOREIGN KEY (sortie_id)
    REFERENCES bill_sortie(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_sortie 
  ADD CONSTRAINT FK_64252CB1F11D9B2F FOREIGN KEY (ligne_stock_controle_id)
    REFERENCES bill_ligne_stock_controle(id);

--
-- Create table `bill_ligne_entree`
--
CREATE TABLE bill_ligne_entree (
  id INT(11) NOT NULL AUTO_INCREMENT,
  produit_site_id INT(11) NOT NULL,
  entree_id INT(11) NOT NULL,
  produit_id INT(11) NOT NULL,
  ligne_stock_controle_id INT(11) NOT NULL,
  quantite DOUBLE NOT NULL,
  observation VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_19988E530469D3F` on table `bill_ligne_entree`
--
ALTER TABLE bill_ligne_entree 
  ADD INDEX IDX_19988E530469D3F(produit_site_id);

--
-- Create index `IDX_19988E5AF7BD910` on table `bill_ligne_entree`
--
ALTER TABLE bill_ligne_entree 
  ADD INDEX IDX_19988E5AF7BD910(entree_id);

--
-- Create index `IDX_19988E5F347EFB` on table `bill_ligne_entree`
--
ALTER TABLE bill_ligne_entree 
  ADD INDEX IDX_19988E5F347EFB(produit_id);

--
-- Create index `UNIQ_19988E5F11D9B2F` on table `bill_ligne_entree`
--
ALTER TABLE bill_ligne_entree 
  ADD UNIQUE INDEX UNIQ_19988E5F11D9B2F(ligne_stock_controle_id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_entree 
  ADD CONSTRAINT FK_19988E530469D3F FOREIGN KEY (produit_site_id)
    REFERENCES bill_produit_site(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_entree 
  ADD CONSTRAINT FK_19988E5AF7BD910 FOREIGN KEY (entree_id)
    REFERENCES bill_entree(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_entree 
  ADD CONSTRAINT FK_19988E5F11D9B2F FOREIGN KEY (ligne_stock_controle_id)
    REFERENCES bill_ligne_stock_controle(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_entree 
  ADD CONSTRAINT FK_19988E5F347EFB FOREIGN KEY (produit_id)
    REFERENCES bill_produit(id);

--
-- Create table `bill_ligne_controle`
--
CREATE TABLE bill_ligne_controle (
  id INT(11) NOT NULL AUTO_INCREMENT,
  controle_id INT(11) NOT NULL,
  produit_site_id INT(11) NOT NULL,
  quantite_physique DOUBLE NOT NULL,
  observation VARCHAR(255) DEFAULT NULL,
  quantite_billcard DOUBLE NOT NULL,
  manquant DOUBLE NOT NULL,
  surplus DOUBLE NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  ligne_stock_controle_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_F86F923F30469D3F` on table `bill_ligne_controle`
--
ALTER TABLE bill_ligne_controle 
  ADD INDEX IDX_F86F923F30469D3F(produit_site_id);

--
-- Create index `IDX_F86F923F758926A6` on table `bill_ligne_controle`
--
ALTER TABLE bill_ligne_controle 
  ADD INDEX IDX_F86F923F758926A6(controle_id);

--
-- Create index `UNIQ_F86F923FF11D9B2F` on table `bill_ligne_controle`
--
ALTER TABLE bill_ligne_controle 
  ADD UNIQUE INDEX UNIQ_F86F923FF11D9B2F(ligne_stock_controle_id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_controle 
  ADD CONSTRAINT FK_F86F923F30469D3F FOREIGN KEY (produit_site_id)
    REFERENCES bill_produit_site(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_controle 
  ADD CONSTRAINT FK_F86F923F758926A6 FOREIGN KEY (controle_id)
    REFERENCES bill_controle(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_controle 
  ADD CONSTRAINT FK_F86F923FF11D9B2F FOREIGN KEY (ligne_stock_controle_id)
    REFERENCES bill_ligne_stock_controle(id);

--
-- Create table `bill_ligne_billcard`
--
CREATE TABLE bill_ligne_billcard (
  id INT(11) NOT NULL AUTO_INCREMENT,
  site_id INT(11) NOT NULL,
  produit_site_id INT(11) NOT NULL,
  ligne_transfert_id INT(11) DEFAULT NULL,
  date DATE NOT NULL,
  machine_number VARCHAR(255) NOT NULL,
  delivery_note_number VARCHAR(255) NOT NULL,
  quantity_received DOUBLE NOT NULL,
  supplier VARCHAR(255) NOT NULL,
  customer VARCHAR(255) NOT NULL,
  id_number VARCHAR(255) NOT NULL,
  quantity_sold DOUBLE NOT NULL,
  total_balance DOUBLE NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_B30C86A30469D3F` on table `bill_ligne_billcard`
--
ALTER TABLE bill_ligne_billcard 
  ADD INDEX IDX_B30C86A30469D3F(produit_site_id);

--
-- Create index `IDX_B30C86A84420B62` on table `bill_ligne_billcard`
--
ALTER TABLE bill_ligne_billcard 
  ADD INDEX IDX_B30C86A84420B62(ligne_transfert_id);

--
-- Create index `IDX_B30C86AF6BD1646` on table `bill_ligne_billcard`
--
ALTER TABLE bill_ligne_billcard 
  ADD INDEX IDX_B30C86AF6BD1646(site_id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_billcard 
  ADD CONSTRAINT FK_B30C86A30469D3F FOREIGN KEY (produit_site_id)
    REFERENCES bill_produit_site(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_billcard 
  ADD CONSTRAINT FK_B30C86A84420B62 FOREIGN KEY (ligne_transfert_id)
    REFERENCES bill_ligne_transfert(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_billcard 
  ADD CONSTRAINT FK_B30C86AF6BD1646 FOREIGN KEY (site_id)
    REFERENCES bill_site(id);

--
-- Create table `ligne_damage`
--
CREATE TABLE ligne_damage (
  id INT(11) NOT NULL AUTO_INCREMENT,
  produit_site_id INT(11) NOT NULL,
  site_id INT(11) NOT NULL,
  ligne_billcard_id INT(11) NOT NULL,
  date DATE NOT NULL,
  quantite DOUBLE NOT NULL,
  observation LONGTEXT DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_3712C82A30469D3F` on table `ligne_damage`
--
ALTER TABLE ligne_damage 
  ADD INDEX IDX_3712C82A30469D3F(produit_site_id);

--
-- Create index `IDX_3712C82AF6BD1646` on table `ligne_damage`
--
ALTER TABLE ligne_damage 
  ADD INDEX IDX_3712C82AF6BD1646(site_id);

--
-- Create index `UNIQ_3712C82AC79BF382` on table `ligne_damage`
--
ALTER TABLE ligne_damage 
  ADD UNIQUE INDEX UNIQ_3712C82AC79BF382(ligne_billcard_id);

--
-- Create foreign key
--
ALTER TABLE ligne_damage 
  ADD CONSTRAINT FK_3712C82A30469D3F FOREIGN KEY (produit_site_id)
    REFERENCES bill_produit_site(id);

--
-- Create foreign key
--
ALTER TABLE ligne_damage 
  ADD CONSTRAINT FK_3712C82AC79BF382 FOREIGN KEY (ligne_billcard_id)
    REFERENCES bill_ligne_billcard(id);

--
-- Create foreign key
--
ALTER TABLE ligne_damage 
  ADD CONSTRAINT FK_3712C82AF6BD1646 FOREIGN KEY (site_id)
    REFERENCES bill_site(id);

--
-- Create table `bill_ligne_reuse`
--
CREATE TABLE bill_ligne_reuse (
  id INT(11) NOT NULL AUTO_INCREMENT,
  produit_site_id INT(11) NOT NULL,
  ligne_billcard_id INT(11) NOT NULL,
  site_id INT(11) NOT NULL,
  date DATE NOT NULL,
  quantite DOUBLE NOT NULL,
  observation LONGTEXT DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_508B04E730469D3F` on table `bill_ligne_reuse`
--
ALTER TABLE bill_ligne_reuse 
  ADD INDEX IDX_508B04E730469D3F(produit_site_id);

--
-- Create index `IDX_508B04E7F6BD1646` on table `bill_ligne_reuse`
--
ALTER TABLE bill_ligne_reuse 
  ADD INDEX IDX_508B04E7F6BD1646(site_id);

--
-- Create index `UNIQ_508B04E7C79BF382` on table `bill_ligne_reuse`
--
ALTER TABLE bill_ligne_reuse 
  ADD UNIQUE INDEX UNIQ_508B04E7C79BF382(ligne_billcard_id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_reuse 
  ADD CONSTRAINT FK_508B04E730469D3F FOREIGN KEY (produit_site_id)
    REFERENCES bill_produit_site(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_reuse 
  ADD CONSTRAINT FK_508B04E7C79BF382 FOREIGN KEY (ligne_billcard_id)
    REFERENCES bill_ligne_billcard(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_reuse 
  ADD CONSTRAINT FK_508B04E7F6BD1646 FOREIGN KEY (site_id)
    REFERENCES bill_site(id);

--
-- Create table `bill_ligne_damage`
--
CREATE TABLE bill_ligne_damage (
  id INT(11) NOT NULL AUTO_INCREMENT,
  produit_site_id INT(11) NOT NULL,
  site_id INT(11) NOT NULL,
  ligne_billcard_id INT(11) NOT NULL,
  date DATE NOT NULL,
  quantite DOUBLE NOT NULL,
  observation LONGTEXT DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_49D2AB2F30469D3F` on table `bill_ligne_damage`
--
ALTER TABLE bill_ligne_damage 
  ADD INDEX IDX_49D2AB2F30469D3F(produit_site_id);

--
-- Create index `IDX_49D2AB2FF6BD1646` on table `bill_ligne_damage`
--
ALTER TABLE bill_ligne_damage 
  ADD INDEX IDX_49D2AB2FF6BD1646(site_id);

--
-- Create index `UNIQ_49D2AB2FC79BF382` on table `bill_ligne_damage`
--
ALTER TABLE bill_ligne_damage 
  ADD UNIQUE INDEX UNIQ_49D2AB2FC79BF382(ligne_billcard_id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_damage 
  ADD CONSTRAINT FK_49D2AB2F30469D3F FOREIGN KEY (produit_site_id)
    REFERENCES bill_produit_site(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_damage 
  ADD CONSTRAINT FK_49D2AB2FC79BF382 FOREIGN KEY (ligne_billcard_id)
    REFERENCES bill_ligne_billcard(id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_damage 
  ADD CONSTRAINT FK_49D2AB2FF6BD1646 FOREIGN KEY (site_id)
    REFERENCES bill_site(id);

--
-- Create table `bill_ligne_sortie_transfert`
--
CREATE TABLE bill_ligne_sortie_transfert (
  id INT(11) NOT NULL AUTO_INCREMENT,
  produit_site_id INT(11) NOT NULL,
  quantite DOUBLE NOT NULL,
  solde DOUBLE NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1489,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_984C98D230469D3F` on table `bill_ligne_sortie_transfert`
--
ALTER TABLE bill_ligne_sortie_transfert 
  ADD INDEX IDX_984C98D230469D3F(produit_site_id);

--
-- Create foreign key
--
ALTER TABLE bill_ligne_sortie_transfert 
  ADD CONSTRAINT FK_984C98D230469D3F FOREIGN KEY (produit_site_id)
    REFERENCES bill_produit_site(id);

--
-- Create table `bill_billcard`
--
CREATE TABLE bill_billcard (
  id INT(11) NOT NULL AUTO_INCREMENT,
  produit_id INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `IDX_709AADFAF347EFB` on table `bill_billcard`
--
ALTER TABLE bill_billcard 
  ADD INDEX IDX_709AADFAF347EFB(produit_id);

--
-- Create foreign key
--
ALTER TABLE bill_billcard 
  ADD CONSTRAINT FK_709AADFAF347EFB FOREIGN KEY (produit_id)
    REFERENCES bill_produit(id);

--
-- Create table `doctrine_migration_versions`
--
CREATE TABLE doctrine_migration_versions (
  version VARCHAR(191) NOT NULL,
  executed_at DATETIME DEFAULT NULL,
  execution_time INT(11) DEFAULT NULL,
  PRIMARY KEY (version)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;